// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuj1hv9MtLIp3zWvs-W0u9MY7IANwVXW4',
    appId: '1:271192488548:android:2bf31d6a2ef8228ee0fd71',
    messagingSenderId: '271192488548',
    projectId: 'my-kitchen-befa7',
    storageBucket: 'my-kitchen-befa7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs29njFZKRV4wsz-BKjZB3h9AJgMIoIE4',
    appId: '1:271192488548:ios:8c3d5149b3789bcbe0fd71',
    messagingSenderId: '271192488548',
    projectId: 'my-kitchen-befa7',
    storageBucket: 'my-kitchen-befa7.appspot.com',
    androidClientId: '271192488548-0afolfe1tclqabup1df6iuhr02k20nog.apps.googleusercontent.com',
    iosClientId: '271192488548-15n8tndcif11nmmlqjn2255shaidoaj2.apps.googleusercontent.com',
    iosBundleId: 'com.mykitchen.myKitchen',
  );
}
